"""liststatus

Revision ID: 50194d8b6c06
Revises: 5ac068d38ce2
Create Date: 2024-08-14 11:03:51.213421

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "50194d8b6c06"
down_revision = "5ac068d38ce2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("list", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status", sa.String(length=255), nullable=False, comment="ステータス"
            )
        )
        batch_op.alter_column(
            "user_id",
            existing_type=mysql.INTEGER(display_width=11),
            comment="親のユーザーID",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "title",
            existing_type=mysql.VARCHAR(length=255),
            comment="リスト名",
            existing_nullable=False,
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "list_id",
            existing_type=mysql.INTEGER(display_width=11),
            comment="親のリストID",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status_id",
            existing_type=mysql.INTEGER(display_width=11),
            comment="ステータス",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "text", existing_type=mysql.TEXT(), comment="内容", existing_nullable=False
        )
        batch_op.alter_column(
            "created",
            existing_type=mysql.DATETIME(),
            comment="作成日時",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated",
            existing_type=mysql.DATETIME(),
            comment="最終更新日時",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "completed",
            existing_type=mysql.DATETIME(),
            comment="完了日時",
            existing_nullable=True,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "user",
            existing_type=mysql.VARCHAR(length=80),
            comment="ユーザーID",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "pass_hash",
            existing_type=mysql.VARCHAR(length=255),
            comment="パスワードハッシュ",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "joined",
            existing_type=mysql.DATETIME(),
            comment="登録日時",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "last_login",
            existing_type=mysql.DATETIME(),
            comment="最終ログイン時刻",
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "last_login",
            existing_type=mysql.DATETIME(),
            comment=None,
            existing_comment="最終ログイン時刻",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "joined",
            existing_type=mysql.DATETIME(),
            comment=None,
            existing_comment="登録日時",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "pass_hash",
            existing_type=mysql.VARCHAR(length=255),
            comment=None,
            existing_comment="パスワードハッシュ",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "user",
            existing_type=mysql.VARCHAR(length=80),
            comment=None,
            existing_comment="ユーザーID",
            existing_nullable=False,
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "completed",
            existing_type=mysql.DATETIME(),
            comment=None,
            existing_comment="完了日時",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated",
            existing_type=mysql.DATETIME(),
            comment=None,
            existing_comment="最終更新日時",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created",
            existing_type=mysql.DATETIME(),
            comment=None,
            existing_comment="作成日時",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "text",
            existing_type=mysql.TEXT(),
            comment=None,
            existing_comment="内容",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status_id",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="ステータス",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "list_id",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="親のリストID",
            existing_nullable=False,
        )

    with op.batch_alter_table("list", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=mysql.VARCHAR(length=255),
            comment=None,
            existing_comment="リスト名",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="親のユーザーID",
            existing_nullable=False,
        )
        batch_op.drop_column("status")

    # ### end Alembic commands ###
