"""last_updated

Revision ID: dee28bfaa55e
Revises: 50194d8b6c06
Create Date: 2025-10-10 17:14:25.277414

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dee28bfaa55e"
down_revision: str | None = "50194d8b6c06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "list",
        sa.Column(
            "last_updated", sa.DateTime(), nullable=False, comment="最終更新日時", server_default=sa.text("CURRENT_TIMESTAMP")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("list", "last_updated")
    # ### end Alembic commands ###
