---
services:
  app:
    image: node:lts
    restart: always
    command: >
      bash -xc '
        mkdir -p ${PWD}/.cache/bin &&
        corepack enable --install-directory ${PWD}/.cache/bin &&
        export PATH=${PWD}/.cache/bin:${PWD}/node_modules/.bin:$$PATH &&
        CI=true pnpm install &&
        exec pnpm run dev
      '
    user: ${UID}:${GID}
    environment:
      - HOME=${PWD}/.cache
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
      - DATABASE_URL=mysql://glatasks:glatasks@db/glatasks
      - DATA_DIR
      - PROTOCOL_HEADER=X-Forwarded-Proto
    volumes:
      - ${PWD}:${PWD}
      - ${DATA_DIR}:${DATA_DIR}
    working_dir: ${PWD}
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy
      migrate-dev:
        condition: service_completed_successfully
    logging:
      options:
        max-size: "1m"
        max-file: "3"
